matrix:
  include:
  - language: python
    python: 3.6
    env: TOXENV=py36
    cache: pip
    before_install:
    - pip install -U pip
    install:
    - pip install -U tox-travis
    script: tox

  - language: python
    python: 3.7
    env: TOXENV=py37
    cache: pip
    before_install:
    - pip install -U pip
    install:
    - pip install -U tox-travis codecov
    script: tox
    after_success: codecov

  - language: python
    python: 3.8
    env: TOXENV=py38
    cache: pip
    before_install:
      - pip install -U pip
    install:
      - pip install -U tox-travis
    script: tox

  - language: python
    python: 3.7
    env: TOXENV=flake8
    cache: pip
    before_install:
    - pip install -U pip
    install:
    - pip install -U tox-travis
    script: tox

after_failure:
# POST all failures on the main branch to Discord
- chmod +x ./notify_failure_discord.sh
- ./notify_failure_discord.sh failure $WEBHOOK_URL

# Deploy a snapshot
before_deploy:
- bump2version patch --allow-dirty --list --new-version '{$(git describe)}' --no-commit --tag-name '{$(git describe)}'
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
