site_name: 'psi-collect'
site_description: 'Collection, aggregation, and cataloging of post-storm imagery.'
site_author: 'PSI Team'
site_url: 'https://psi-collect.readthedocs.io/en/master/'

repo_url: 'https://github.com/UNCG-DAISY/psi-collect/'
edit_uri: 'edit/master/docs/'

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Usage:
      - Data Collection: collector.md
      - Cataloging Images: cataloging.md
    - Development:
      - Code Conventions: contributing.md
      - Configuring Module: configure_python_path.md
      - Distribution & PyPI: distributing_pypi.md
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'light green'

# Dark theme from https://github.com/fmaida/mkdocs-material-dark-theme
# This works well with the admonition extension
extra_css:
    - stylesheets/extra.css
    # - stylesheets/extra.css.map
    # - stylesheets/extra.scss
#   - stylesheets/dark_theme.css
#   - stylesheets/codehilite.css

plugins:
    - search
    - git-revision-date
    - macros

markdown_extensions:
    - toc
    - admonition
    - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: monokai
    - footnotes
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
    version: 1.0.1
